export interface CuratedModel {
  id: string;
  name: string;
  repo: string;
  parameter_size: string;
  real_size_gb: string;
  likes: number;
  downloads: number;
  weight_format: string;
  bit_precision: string;
  available_quantizations?: string[];
  license: string;
  context_window: string;
  tags: string[];
}

export const CURATED_DEFAULT_MODELS: CuratedModel[] = [
  {
    id: "unsloth/Kimi-K2.7-Code-GGUF",
    name: "Kimi K2.7 Code GGUF (1T MoE)",
    repo: "unsloth/Kimi-K2.7-Code-GGUF",
    parameter_size: "1T MoE (1 Trillion)",
    real_size_gb: "490.0 GB",
    likes: 189,
    downloads: 180000,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-IQ4_XS)",
    available_quantizations: ["UD-IQ1_M", "UD-IQ2_M", "UD-IQ2_XXS", "UD-IQ3_S", "UD-IQ4_XS", "UD-Q2_K_XL", "UD-Q3_K_M", "UD-Q3_K_XL", "UD-Q4_K_XL", "UD-Q8_K_XL"],
    license: "Moonshot Open",
    context_window: "128K Tokens",
    tags: ["kimi", "kimi-k2.7", "1t", "moe", "unsloth", "gguf", "text-generation"],
  },
  {
    id: "microsoft/Fara1.5-27B",
    name: "Fara 1.5 27B",
    repo: "microsoft/Fara1.5-27B",
    parameter_size: "27.0B",
    real_size_gb: "54.0 GB",
    likes: 1420,
    downloads: 320000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "MIT",
    context_window: "128K Tokens",
    tags: ["microsoft", "fara", "text-generation"],
  },
  {
    id: "poolside/Laguna-S-2.1",
    name: "Laguna-S 2.1 (140B MoE)",
    repo: "poolside/Laguna-S-2.1",
    parameter_size: "140B MoE",
    real_size_gb: "280.0 GB",
    likes: 980,
    downloads: 210000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["poolside", "laguna", "140b", "moe", "text-generation"],
  },
  {
    id: "unsloth/Laguna-S-2.1-GGUF",
    name: "Laguna-S 2.1 GGUF (140B MoE)",
    repo: "unsloth/Laguna-S-2.1-GGUF",
    parameter_size: "140B MoE",
    real_size_gb: "84.0 GB",
    likes: 650,
    downloads: 140000,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-Q4_K_M)",
    available_quantizations: ["UD-IQ2_XXS", "UD-IQ3_S", "UD-IQ4_XS", "UD-Q4_K_M", "UD-Q5_K_M", "UD-Q8_0"],
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["poolside", "laguna", "140b", "unsloth", "gguf", "text-generation"],
  },
  {
    id: "Qwen/Qwen3.6-35B-A3B",
    name: "Qwen 3.6 35B A3B",
    repo: "Qwen/Qwen3.6-35B-A3B",
    parameter_size: "35.0B",
    real_size_gb: "70.0 GB",
    likes: 3400,
    downloads: 890000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["qwen", "qwen3.6", "alibaba", "text-generation"],
  },
  {
    id: "DavidAU/Qwen3.5-9B-The-Defiant-Fable-Uncensored-Heretic-NEO-IMATRIX-MAX-MTP-GGUF",
    name: "Qwen 3.5 9B Defiant Fable Uncensored GGUF",
    repo: "DavidAU/Qwen3.5-9B-The-Defiant-Fable-Uncensored-Heretic-NEO-IMATRIX-MAX-MTP-GGUF",
    parameter_size: "9.0B",
    real_size_gb: "5.4 GB",
    likes: 840,
    downloads: 195000,
    weight_format: "GGUF",
    bit_precision: "4-bit (Q4_K_M)",
    available_quantizations: ["IQ4_NL", "Q4_K_M", "Q5_K_M", "Q8_0"],
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["qwen", "davidau", "uncensored", "gguf", "text-generation"],
  },
  {
    id: "empero-ai/Qwythos-9B-Claude-Mythos-5-1M-GGUF",
    name: "Qwythos 9B Claude Mythos 5 GGUF",
    repo: "empero-ai/Qwythos-9B-Claude-Mythos-5-1M-GGUF",
    parameter_size: "9.0B",
    real_size_gb: "5.4 GB",
    likes: 420,
    downloads: 88000,
    weight_format: "GGUF",
    bit_precision: "4-bit (Q4_K_M)",
    available_quantizations: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    license: "Apache 2.0",
    context_window: "1M Tokens",
    tags: ["qwythos", "mythos", "gguf", "text-generation"],
  },
  {
    id: "yuxinlu1/gemma-4-12B-agentic-fable5-composer2.5-v2-3.5x-tau2-GGUF",
    name: "Gemma 4 12B Agentic Fable5 GGUF",
    repo: "yuxinlu1/gemma-4-12B-agentic-fable5-composer2.5-v2-3.5x-tau2-GGUF",
    parameter_size: "12.0B",
    real_size_gb: "7.2 GB",
    likes: 610,
    downloads: 115000,
    weight_format: "GGUF",
    bit_precision: "4-bit (Q4_K_M)",
    available_quantizations: ["IQ4_XS", "Q4_K_M", "Q5_K_M", "Q8_0"],
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "agentic", "gguf", "text-generation"],
  },
  {
    id: "deepseek-ai/DeepSeek-V4-Flash",
    name: "DeepSeek V4 Flash (160B MoE)",
    repo: "deepseek-ai/DeepSeek-V4-Flash",
    parameter_size: "160B MoE",
    real_size_gb: "320.0 GB",
    likes: 5600,
    downloads: 2400000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "MIT",
    context_window: "128K Tokens",
    tags: ["deepseek", "deepseek-v4", "flash", "moe", "text-generation"],
  },
  {
    id: "google/gemma-4-31B-it",
    name: "Gemma 4 31B Instruct",
    repo: "google/gemma-4-31B-it",
    parameter_size: "31.0B",
    real_size_gb: "62.0 GB",
    likes: 4100,
    downloads: 1800000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "gemma4", "google", "text-generation"],
  },
  {
    id: "unsloth/Qwen3.6-27B-MTP-GGUF",
    name: "Qwen 3.6 27B MTP GGUF",
    repo: "unsloth/Qwen3.6-27B-MTP-GGUF",
    parameter_size: "27.0B",
    real_size_gb: "16.2 GB",
    likes: 1280,
    downloads: 340000,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-Q4_K_M)",
    available_quantizations: ["UD-IQ2_XXS", "UD-IQ3_S", "UD-IQ4_XS", "UD-Q4_K_M", "UD-Q5_K_M", "UD-Q8_0"],
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["qwen", "qwen3.6", "unsloth", "gguf", "text-generation"],
  },
  {
    id: "poolside/Laguna-XS-2.1-GGUF",
    name: "Laguna-XS 2.1 GGUF (21B MoE)",
    repo: "poolside/Laguna-XS-2.1-GGUF",
    parameter_size: "21B MoE",
    real_size_gb: "12.6 GB",
    likes: 510,
    downloads: 95000,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-Q4_K_M)",
    available_quantizations: ["UD-IQ3_S", "UD-IQ4_XS", "UD-Q4_K_M", "UD-Q5_K_M", "UD-Q8_0"],
    license: "Apache 2.0",
    context_window: "64K Tokens",
    tags: ["poolside", "laguna", "21b", "gguf", "text-generation"],
  },
  {
    id: "Qwen/Qwen3-8B",
    name: "Qwen 3 8B",
    repo: "Qwen/Qwen3-8B",
    parameter_size: "8.0B",
    real_size_gb: "16.0 GB",
    likes: 4900,
    downloads: 2900000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["qwen", "qwen3", "alibaba", "text-generation"],
  },
  {
    id: "google/gemma-4-12B-it",
    name: "Gemma 4 12B Instruct",
    repo: "google/gemma-4-12B-it",
    parameter_size: "12.0B",
    real_size_gb: "24.0 GB",
    likes: 3200,
    downloads: 1400000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "gemma4", "google", "text-generation"],
  },
  {
    id: "MiniMaxAI/MiniMax-M3",
    name: "MiniMax M3 (456B MoE)",
    repo: "MiniMaxAI/MiniMax-M3",
    parameter_size: "456B MoE",
    real_size_gb: "912.0 GB",
    likes: 2100,
    downloads: 750000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["minimax", "minimax-m3", "456b", "moe", "text-generation"],
  },
  {
    id: "google/gemma-4-26B-A4B-it",
    name: "Gemma 4 26B A4B Instruct",
    repo: "google/gemma-4-26B-A4B-it",
    parameter_size: "26.0B",
    real_size_gb: "52.0 GB",
    likes: 2800,
    downloads: 920000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "gemma4", "google", "text-generation"],
  },
  {
    id: "tencent/Hy3",
    name: "Tencent Hy3 (108B MoE)",
    repo: "tencent/Hy3",
    parameter_size: "108B MoE",
    real_size_gb: "216.0 GB",
    likes: 1800,
    downloads: 610000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Tencent Open",
    context_window: "128K Tokens",
    tags: ["tencent", "hy3", "108b", "moe", "text-generation"],
  },
  {
    id: "Qwen/Qwen3.5-9B",
    name: "Qwen 3.5 9B",
    repo: "Qwen/Qwen3.5-9B",
    parameter_size: "9.0B",
    real_size_gb: "18.0 GB",
    likes: 3900,
    downloads: 1900000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["qwen", "qwen3.5", "alibaba", "text-generation"],
  },
  {
    id: "openai/gpt-oss-120b",
    name: "OpenAI GPT OSS 120B",
    repo: "openai/gpt-oss-120b",
    parameter_size: "120.0B",
    real_size_gb: "240.0 GB",
    likes: 9800,
    downloads: 4100000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "MIT",
    context_window: "128K Tokens",
    tags: ["openai", "gpt-oss", "120b", "text-generation"],
  },
  {
    id: "google/gemma-4-E4B-it",
    name: "Gemma 4 E4B Instruct",
    repo: "google/gemma-4-E4B-it",
    parameter_size: "4.0B",
    real_size_gb: "8.0 GB",
    likes: 1900,
    downloads: 810000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "gemma4", "google", "text-generation"],
  },
  {
    id: "openai/gpt-oss-20b",
    name: "OpenAI GPT OSS 20B",
    repo: "openai/gpt-oss-20b",
    parameter_size: "20.0B",
    real_size_gb: "40.0 GB",
    likes: 5400,
    downloads: 2300000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "MIT",
    context_window: "128K Tokens",
    tags: ["openai", "gpt-oss", "text-generation"],
  },
  {
    id: "google/gemma-4-E2B-it",
    name: "Gemma 4 E2B Instruct",
    repo: "google/gemma-4-E2B-it",
    parameter_size: "2.0B",
    real_size_gb: "4.0 GB",
    likes: 1500,
    downloads: 640000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Gemma Terms",
    context_window: "32K Tokens",
    tags: ["gemma", "gemma4", "google", "text-generation"],
  },
  {
    id: "XiaomiMiMo/MiMo-V2.5",
    name: "Xiaomi MiMo V2.5 (250B MoE)",
    repo: "XiaomiMiMo/MiMo-V2.5",
    parameter_size: "250B MoE",
    real_size_gb: "500.0 GB",
    likes: 1650,
    downloads: 480000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["xiaomi", "mimo", "250b", "moe", "text-generation"],
  },
  {
    id: "google/embeddinggemma-300m",
    name: "Embedding Gemma 300M",
    repo: "google/embeddinggemma-300m",
    parameter_size: "0.3B",
    real_size_gb: "0.6 GB",
    likes: 2900,
    downloads: 1500000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Gemma Terms",
    context_window: "8K Tokens",
    tags: ["gemma", "embedding", "google"],
  },
  {
    id: "AngelSlim/Hy3-GGUF",
    name: "Tencent Hy3 GGUF (108B MoE)",
    repo: "AngelSlim/Hy3-GGUF",
    parameter_size: "108B MoE",
    real_size_gb: "64.8 GB",
    likes: 490,
    downloads: 92000,
    weight_format: "GGUF",
    bit_precision: "4-bit (Q4_K_M)",
    available_quantizations: ["Q4_K_M", "Q5_K_M", "Q8_0"],
    license: "Tencent Open",
    context_window: "128K Tokens",
    tags: ["tencent", "hy3", "108b", "gguf", "text-generation"],
  },
  {
    id: "google/gemma-4-E2B",
    name: "Gemma 4 E2B Base",
    repo: "google/gemma-4-E2B",
    parameter_size: "2.0B",
    real_size_gb: "4.0 GB",
    likes: 1100,
    downloads: 430000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Gemma Terms",
    context_window: "32K Tokens",
    tags: ["gemma", "gemma4", "google", "text-generation"],
  },
  {
    id: "google/gemma-4-12B",
    name: "Gemma 4 12B Base",
    repo: "google/gemma-4-12B",
    parameter_size: "12.0B",
    real_size_gb: "24.0 GB",
    likes: 2100,
    downloads: 780000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "gemma4", "google", "text-generation"],
  },
  {
    id: "mistralai/Mistral-Medium-3.5-128B",
    name: "Mistral Medium 3.5 128B",
    repo: "mistralai/Mistral-Medium-3.5-128B",
    parameter_size: "128.0B",
    real_size_gb: "256.0 GB",
    likes: 7400,
    downloads: 3100000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["mistral", "mistral-medium", "128b", "text-generation"],
  },
  {
    id: "google/gemma-4-31B",
    name: "Gemma 4 31B Base",
    repo: "google/gemma-4-31B",
    parameter_size: "31.0B",
    real_size_gb: "62.0 GB",
    likes: 2900,
    downloads: 890000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "gemma4", "google", "text-generation"],
  },
  {
    id: "Qwen/Qwen3.5-122B-A10B",
    name: "Qwen 3.5 122B A10B",
    repo: "Qwen/Qwen3.5-122B-A10B",
    parameter_size: "122.0B",
    real_size_gb: "244.0 GB",
    likes: 6100,
    downloads: 2200000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Qwen Research",
    context_window: "128K Tokens",
    tags: ["qwen", "qwen3.5", "122b", "alibaba", "text-generation"],
  },
  {
    id: "google/gemma-4-26B-A4B",
    name: "Gemma 4 26B A4B Base",
    repo: "google/gemma-4-26B-A4B",
    parameter_size: "26.0B",
    real_size_gb: "52.0 GB",
    likes: 1900,
    downloads: 540000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "gemma4", "google", "text-generation"],
  },
  {
    id: "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
    name: "Qwen 3 Coder 30B GGUF",
    repo: "unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF",
    parameter_size: "30.0B",
    real_size_gb: "18.0 GB",
    likes: 1650,
    downloads: 420000,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-Q4_K_M)",
    available_quantizations: ["UD-IQ2_XXS", "UD-IQ3_S", "UD-IQ4_XS", "UD-Q4_K_M", "UD-Q5_K_M", "UD-Q8_0"],
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["qwen", "qwen3", "coder", "unsloth", "gguf", "text-generation"],
  },
  {
    id: "Qwen/Qwen3-Coder-Next",
    name: "Qwen 3 Coder Next",
    repo: "Qwen/Qwen3-Coder-Next",
    parameter_size: "30.0B",
    real_size_gb: "60.0 GB",
    likes: 2900,
    downloads: 1100000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["qwen", "qwen3", "coder", "text-generation"],
  },
  {
    id: "Qwen/Qwen3-Coder-Next-GGUF",
    name: "Qwen 3 Coder Next GGUF",
    repo: "Qwen/Qwen3-Coder-Next-GGUF",
    parameter_size: "30.0B",
    real_size_gb: "18.0 GB",
    likes: 1850,
    downloads: 590000,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-Q4_K_M)",
    available_quantizations: ["UD-IQ2_XXS", "UD-IQ3_S", "UD-IQ4_XS", "UD-Q4_K_M", "UD-Q5_K_M", "UD-Q8_0"],
    license: "Apache 2.0",
    context_window: "128K Tokens",
    tags: ["qwen", "qwen3", "coder", "gguf", "text-generation"],
  },
  {
    id: "zai-org/GLM-4.7-Flash",
    name: "GLM 4.7 Flash (30B MoE)",
    repo: "zai-org/GLM-4.7-Flash",
    parameter_size: "30B MoE",
    real_size_gb: "60.0 GB",
    likes: 1420,
    downloads: 480000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "GLM Open",
    context_window: "128K Tokens",
    tags: ["glm", "glm4.7", "flash", "text-generation"],
  },
  {
    id: "unsloth/GLM-5.2-GGUF",
    name: "GLM 5.2 GGUF (104B MoE)",
    repo: "unsloth/GLM-5.2-GGUF",
    parameter_size: "104B MoE",
    real_size_gb: "62.4 GB",
    likes: 609,
    downloads: 29100,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-Q4_K_M)",
    available_quantizations: ["UD-IQ1_M", "UD-IQ1_S", "UD-IQ2_M", "UD-IQ2_XXS", "UD-IQ3_S", "UD-IQ3_XXS", "UD-IQ4_NL", "UD-IQ4_XS", "UD-Q2_K_XL", "UD-Q3_K_M", "UD-Q3_K_XL", "UD-Q4_K_M", "UD-Q4_K_S", "UD-Q4_K_XL", "UD-Q5_K_M", "Q8_0", "BF16"],
    license: "GLM Open",
    context_window: "128K Tokens",
    tags: ["glm", "glm5.2", "104b", "moe", "unsloth", "gguf", "text-generation"],
  },
  {
    id: "zai-org/GLM-5.2",
    name: "GLM 5.2 Base (104B MoE)",
    repo: "zai-org/GLM-5.2",
    parameter_size: "104B MoE",
    real_size_gb: "208.0 GB",
    likes: 2100,
    downloads: 790000,
    weight_format: "Safetensors",
    bit_precision: "16-bit (FP16)",
    license: "GLM Open",
    context_window: "128K Tokens",
    tags: ["glm", "glm5.2", "104b", "moe", "text-generation"],
  },
  {
    id: "unsloth/gemma-4-12b-it-GGUF",
    name: "Gemma 4 12B Instruct GGUF",
    repo: "unsloth/gemma-4-12b-it-GGUF",
    parameter_size: "12.0B",
    real_size_gb: "7.2 GB",
    likes: 890,
    downloads: 142000,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-Q4_K_M)",
    available_quantizations: ["UD-IQ2_XXS", "UD-IQ3_S", "UD-IQ4_XS", "UD-Q4_K_M", "UD-Q5_K_M", "UD-Q8_0", "BF16"],
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "gemma4", "unsloth", "gguf", "text-generation"],
  },
  {
    id: "unsloth/gemma-4-26B-A4B-it-GGUF",
    name: "Gemma 4 26B A4B GGUF",
    repo: "unsloth/gemma-4-26B-A4B-it-GGUF",
    parameter_size: "26.0B",
    real_size_gb: "15.6 GB",
    likes: 640,
    downloads: 98000,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-Q4_K_M)",
    available_quantizations: ["UD-IQ2_XXS", "UD-IQ3_S", "UD-IQ4_XS", "UD-Q4_K_M", "UD-Q5_K_M", "UD-Q8_0", "BF16"],
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "gemma4", "unsloth", "gguf", "text-generation"],
  },
  {
    id: "unsloth/gemma-4-31B-it-GGUF",
    name: "Gemma 4 31B Instruct GGUF",
    repo: "unsloth/gemma-4-31B-it-GGUF",
    parameter_size: "31.0B",
    real_size_gb: "18.6 GB",
    likes: 1120,
    downloads: 185000,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-Q4_K_M)",
    available_quantizations: ["UD-IQ2_XXS", "UD-IQ3_S", "UD-IQ4_XS", "UD-Q4_K_M", "UD-Q5_K_M", "UD-Q8_0", "BF16"],
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "gemma4", "unsloth", "gguf", "text-generation"],
  },
  {
    id: "unsloth/gemma-4-E2B-it-GGUF",
    name: "Gemma 4 E2B Instruct GGUF",
    repo: "unsloth/gemma-4-E2B-it-GGUF",
    parameter_size: "2.0B",
    real_size_gb: "1.2 GB",
    likes: 420,
    downloads: 76000,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-Q4_K_M)",
    available_quantizations: ["UD-IQ2_XXS", "UD-IQ3_S", "UD-IQ4_XS", "UD-Q4_K_M", "UD-Q5_K_M", "UD-Q8_0", "BF16"],
    license: "Gemma Terms",
    context_window: "32K Tokens",
    tags: ["gemma", "gemma4", "unsloth", "gguf", "text-generation"],
  },
  {
    id: "unsloth/gemma-4-E4B-it-GGUF",
    name: "Gemma 4 E4B Instruct GGUF",
    repo: "unsloth/gemma-4-E4B-it-GGUF",
    parameter_size: "4.0B",
    real_size_gb: "2.4 GB",
    likes: 560,
    downloads: 92000,
    weight_format: "GGUF",
    bit_precision: "4-bit (UD-Q4_K_M)",
    available_quantizations: ["UD-IQ2_XXS", "UD-IQ3_S", "UD-IQ4_XS", "UD-Q4_K_M", "UD-Q5_K_M", "UD-Q8_0", "BF16"],
    license: "Gemma Terms",
    context_window: "128K Tokens",
    tags: ["gemma", "gemma4", "unsloth", "gguf", "text-generation"],
  },
];

export function getFallbackModels(queryStr: string = ""): CuratedModel[] {
  const q = queryStr.trim().toLowerCase();
  if (!q) return CURATED_DEFAULT_MODELS;
  return CURATED_DEFAULT_MODELS.filter(
    (m) =>
      m.id.toLowerCase().includes(q) ||
      m.name.toLowerCase().includes(q) ||
      m.repo.toLowerCase().includes(q) ||
      m.tags.some((t) => t.toLowerCase().includes(q))
  );
}
